---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: send NETCONF 1.1 XML file
    iosxr_nc11_send:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      xmlfile: '{{ xml_file }}'
    register: output
  - debug: var=output.stdout_lines
