---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: get system facts
    iosxr_get_facts:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
    register: facts
  - debug: var=facts
