---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_command:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      commands: 'show logging'
    register: output
  - debug: var=output.stdout_lines
