---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    smu_name: 'xrv9k-li-x-1.1.0.0-r65106I'

  tasks:
  - name: add SMU package
    iosxr_install_package:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      pkgpath: 'tftp://192.168.1.30'
      pkgname: '{{ smu_name }}'
      state: present
    register: output
  - debug: var=output.stdout_lines

  - name: activate SMU package
    iosxr_install_package:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      pkgname: '{{ smu_name }}'
      state: activated
    register: output
  - debug: var=output.stdout_lines
