---
- hosts: 192.168.1.3
  connection: local
  gather_facts: no

  tasks:
  - name: apply configuration file on the IOS-XR node
    iosxr_install_config:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      cfgname: 'tftp://192.168.1.1/chg_ss1.cfg'
      replace: true
    register: output
  - debug: var=output.stdout_lines
