---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: get IOS-XR running configuration
    iosxr_get_config:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
    register: output
  - debug: var=output.stdout_lines
