---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: remove user cisco
    iosxr_config:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      commands: 'no username cisco'
      force: True
    register: output
  - debug: var=output.updates
