---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: IOS-XR file copy
    iosxr_file_copy:
      host: "{{ ansible_host }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_pass }}"
      path: "{{ path }}"
      filename: "{{ filename }}"
      direction: "{{ dir }}"
    register: output
  - debug: var=output.stdout_lines
