---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: replace configuration file on the IOS-XR node
    iosxr_install_config:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      cfgname: 'tftp://192.168.1.1/user_mod.cfg'
    register: output
  - debug: var=output.stdout_lines
