---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_install_key:
      host: "{{ ansible_host }}"
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      keyfile: 'tftp://192.168.1.1/id_rsa_pub.b64'
    register: output
  - debug: var=output.stdout_lines
