---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    smu_name: 'mem:asr9k-mpls-px-6.1.1.02I'

  tasks:
  - name: deactivate SMU package
    xr32_install_package:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      pkgname: '{{ smu_name }}'
      state: deactivated
    register: output
  - debug: var=output.stdout_lines

  - name: remove SMU package
    xr32_install_package:
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      pkgname: '{{ smu_name }}'
      state: absent
    register: output
  - debug: var=output.stdout_lines
