---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - name: run IOS-XR CLI command
    shell: 'ssh -p 57722 {{ ansible_ssh_user}}@{{ ansible_host }} "source /etc/profile; nsenter -t 1 -n -- xr_cli \"{{ cmd }}\""'
    register: output
  - debug: var=output.stdout_lines
