---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_show_install_log:
      host: "{{ ansible_host }}"
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
    register: output
  - debug: var=output.stdout_lines
