---
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - iosxr_command:
      host: "{{ ansible_host }}"
      username: '{{ ansible_ssh_user }}'
      commands: 'show running-config'
    register: output
  - debug: var=output.stdout_lines
