---
- hosts: ss-xr
  gather_facts: no

  tasks:
  - iosxr_cli:
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      command: "{{ cmd }}"
    register: output
  - debug: var=output.stdout_lines
