---
- hosts: ss-xr
  gather_facts: no

  tasks:
  - name: remove user cisco
    iosxr_install_config:
      username: '{{ ansible_ssh_user }}'
      cfgname: '/tftp://192.168.1.1/user_remove.cfg'
    register: output
  - debug: var=output.stdout_lines
