---
- hosts: ss-xr
  gather_facts: no

  vars:
    smu_name: 'xrv9k-mpls-2.0.0.1-r60204I.CSCxr33333'

  tasks:
  - name: deactivate SMU package
    iosxr_install_package:
      username: '{{ ansible_ssh_user }}'
      pkgname: '{{ smu_name }}'
      state: deactivated
    register: output
  - debug: var=output.stdout_lines

  - name: remove SMU package
    iosxr_install_package:
      username: '{{ ansible_ssh_user }}'
      pkgname: '{{ smu_name }}'
      state: absent
    register: output
  - debug: var=output.stdout_lines
