---
- hosts: ss-xr
  gather_facts: no

  tasks:
  - name: get IOS-XR running configuration
    iosxr_get_config:
      username: '{{ ansible_ssh_user }}'
    register: output
  - debug: var=output.stdout_lines
